<script lang="ts">
    import Select from "$lib/widgets/Select.svelte";
    import JsonValueEditor from "./valueEditors/JsonValueEditor.svelte";
    import type {PgColumn, PgRow} from "./pgContext.svelte";
    import {valueToSql} from "./values";
    import TextValueEditor from "./valueEditors/TextValueEditor.svelte";
    import EnumValueEditor from "./valueEditors/EnumValueEditor.svelte";
    import FKEditor from "./valueEditors/FKEditor.svelte";

    type Props = {
        inlined: boolean;
        column: PgColumn;
        row: PgRow;
    };
    let {column, row = $bindable(), inlined}: Props = $props();
</script>

{#if column.is_nullable === "YES" && row[column.column_name] === null}
    <div class="p-2 text-sm text-fg-1 border border-bg-2 rounded-xl">
        This value is set to null, untick the NULL checkbox to apply a value.
    </div>
{:else if column.is_primary_key === "YES"}
    {#if row[column.column_name] === null}
        <div class="p-2 text-sm text-fg-1 border border-bg-2 rounded-xl">
            The primary key will be automatically generated by postgres.
        </div>
    {:else}
        <input
            id={column.column_name}
            type="text"
            class="font-mono! w-full"
            autocorrect="off"
            autocomplete="off"
            autocapitalize="off"
            disabled={true}
            placeholder={(row[column.column_name] as string) ?? "generated"}
        />
    {/if}
{:else if column.foreign_column_name !== null}
    <FKEditor bind:value={row[column.column_name] as string} {column} {inlined} />
{:else if column.enum_values}
    <EnumValueEditor {column} bind:value={row[column.column_name] as string} {inlined} />
{:else if column.data_type === "boolean" || column.data_type === "bool"}
    <Select
        class="font-mono font-normal! w-full"
        id={column.column_name}
        bind:value={() => valueToSql(column, row[column.column_name]), (value) => (row[column.column_name] = value)}
    >
        <option>true</option>
        <option>false</option>
    </Select>
{:else if column.data_type === "json" || column.data_type === "jsonb"}
    <JsonValueEditor
        bind:value={
            () => JSON.stringify(row[column.column_name], null, 4),
            (newValue) => {
                row[column.column_name] = JSON.parse(newValue);
            }
        }
        {column}
        {inlined}
    />
{:else if column.data_type === "tsvector"}
    <input
        id={column.column_name}
        type="text"
        class="font-mono!"
        autocorrect="off"
        autocomplete="off"
        autocapitalize="off"
        disabled={true}
        placeholder="generated"
    />
{:else}
    <TextValueEditor bind:value={row[column.column_name] as string} {column} {inlined} />
{/if}
