<script lang="ts">
    import Select from "$lib/widgets/Select.svelte";
    import type {PgColumn, PgRow} from "./tableContext.svelte";

    type Props = {
        column: PgColumn;
        row: PgRow;
    };
    let {column, row = $bindable()}: Props = $props();

    let rowValue = {
        get value() {
            if (typeof row[column.column_name] === "object") {
                return JSON.stringify(row[column.column_name]);
            }
            return row[column.column_name] as string;
        },
        set value(newValue) {
            if (typeof newValue === "object" && newValue !== null) {
                row[column.column_name] = JSON.parse(newValue);
            } else {
                row[column.column_name] = newValue;
            }
        },
    };
    const disabled = $derived.by(() => {
        if (column.is_primary_key === "YES") {
            return true;
        }
        if (column.is_nullable === "YES" && row[column.column_name] === null) {
            return true;
        }
        return false;
    });

    const placeholder = $derived.by(() => {
        if (column.is_primary_key === "YES" && !row[column.column_name]) {
            return "Generated by default";
        } else if (
            (column.is_nullable === "YES" && row[column.column_name] === null) ||
            row[column.column_name] === undefined
        ) {
            return "null";
        }
        return "Enter a value";
    });
</script>

{#if column.enum_values}
    <!-- TODO: handle null properly -->
    <Select id={column.column_name} {disabled} bind:value={row[column.column_name]}>
        {#each column.enum_values as enumValue}
            <option>{enumValue}</option>
        {/each}
    </Select>
{:else}
    <input
        id={column.column_name}
        type="text"
        class="font-mono!"
        autocorrect="off"
        {disabled}
        {placeholder}
        bind:value={rowValue.value}
    />
{/if}
