<script lang="ts">
    import CrossIcon from "$lib/icons/CrossIcon.svelte";
    import MonacoEditor from "$lib/monaco/MonacoEditor.svelte";
    import Dialog from "$lib/widgets/Dialog.svelte";
    import MultilinesInput from "$lib/widgets/MultilinesInput.svelte";
    import Select from "$lib/widgets/Select.svelte";
    import type {PgColumn, PgRow} from "./tableContext.svelte";
    import {formatValue} from "./values";

    type Props = {
        column: PgColumn;
        row: PgRow;
    };
    let {column, row = $bindable()}: Props = $props();

    let rowValue = {
        get value() {
            if (typeof row[column.column_name] === "object") {
                return JSON.stringify(row[column.column_name]);
            }
            return row[column.column_name] as string;
        },
        set value(newValue) {
            if (typeof newValue === "object" && newValue !== null) {
                row[column.column_name] = JSON.parse(newValue);
            } else {
                row[column.column_name] = newValue;
            }
        },
    };
    const disabled = $derived.by(() => {
        if (column.is_primary_key === "YES") {
            return true;
        }
        if (column.is_nullable === "YES" && row[column.column_name] === null) {
            return true;
        }
        return false;
    });

    const placeholder = $derived.by(() => {
        if (column.is_primary_key === "YES" && !row[column.column_name]) {
            return "Generated by default";
        } else if (
            (column.is_nullable === "YES" && row[column.column_name] === null) ||
            row[column.column_name] === undefined
        ) {
            return "null";
        }
        return "Enter a value";
    });

    let isMonacoOpen = $state(false);
</script>

{#if column.enum_values && row[column.column_name] !== null}
    <Select class="font-mono font-normal!" id={column.column_name} {disabled} bind:value={row[column.column_name]}>
        {#each column.enum_values as enumValue}
            <option>{enumValue}</option>
        {/each}
    </Select>
{:else if column.data_type === "boolean" || column.data_type === "bool"}
    <Select
        class="font-mono font-normal!"
        id={column.column_name}
        {disabled}
        bind:value={() => formatValue(column, row[column.column_name]), (value) => (row[column.column_name] = value)}
    >
        {#if typeof row[column.column_name] === "boolean" || typeof row[column.column_name] === "string"}
            <option>true</option>
            <option>false</option>
        {:else}
            <option value="" disabled>null</option>
        {/if}
    </Select>
{:else if ["text", "xml"].includes(column.data_type)}
    <MultilinesInput
        id={column.column_name}
        class="font-mono!"
        {disabled}
        {placeholder}
        minRows={1}
        bind:value={rowValue.value}
    />
{:else if ["json", "jsonb"].includes(column.data_type)}
    <div class="min-h-40 border border-bg-1">
        <MonacoEditor
            bind:value={rowValue.value}
            selectedFile="value.json"
            files={[{path: "value.json", value: ""}]}
            fontFamily="Space Mono"
            fontSize={12}
            showLineNumbers={false}
            onchange={(value, path) => {
                switch (path) {
                    case "value.json":
                        rowValue.value = value;
                        break;
                    default:
                        throw new Error(`File ${path} not found.`);
                }
            }}
        />
    </div>
    <!-- <div class="relative">
        <MultilinesInput
            id={column.column_name}
            class="font-mono!"
            {disabled}
            {placeholder}
            minRows={1}
            bind:value={rowValue.value}
        />
        {#if ["json", "jsonb", "xml"].includes(column.data_type)}
            <button
                class="cursor-pointer absolute top-2 right-2 bg-bg border border-bg-1 rounded-xl text-sm! px-2 py-1"
                onclick={() => (isMonacoOpen = true)}>Edit</button
            >
            <Dialog
                isOpen={isMonacoOpen}
                onrequestclose={() => (isMonacoOpen = false)}
                position="right"
                animation="right"
            >
                <header class="flex gap-4 w-xl pb-2 items-center">
                    <button
                        type="button"
                        class="btn icon ghost"
                        aria-label="Close"
                        onclick={(e) => {
                            isMonacoOpen = false;
                            e.stopPropagation();
                        }}><CrossIcon /></button
                    >
                    <h2 class="flex gap-2">
                        <span>Editing</span>
                        <span class="font-mono text-sm bg-bg-1 py-0.5 px-2 rounded-md ml-1">{column.column_name}</span>
                        <span class="font-normal">{column.data_type}</span>
                    </h2>
                </header>
                <MonacoEditor
                    bind:value={rowValue.value}
                    selectedFile="value.json"
                    files={[{path: "value.json", value: ""}]}
                    fontSize={12}
                    onchange={(value, path) => {
                        switch (path) {
                            case "value.json":
                                rowValue.value = value;
                                break;
                            default:
                                throw new Error(`File ${path} not found.`);
                        }
                    }}
                />
            </Dialog>
        {/if}
    </div> -->
{:else}
    <input
        id={column.column_name}
        type="text"
        class="font-mono!"
        autocorrect="off"
        {disabled}
        {placeholder}
        bind:value={rowValue.value}
    />
{/if}
